[package]
name = "refpack"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
description = "A crate providing compression/decompression for the RefPack compression format, utilized by many early 2000s EA games"
authors = ["actioninja"]
license = "MPL-2.0"
categories = ["compression", "game-development"]
keywords = ["refpack", "dbpf", "far", "ea", "qfs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
byteorder = "1.4.3"
binrw = "0.8.0"

[dev-dependencies]
proptest = "1.0.0"
test-strategy = "0.1.2"
